// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyBalance = `-- name: ApplyBalance :execrows
UPDATE account_balances
   SET posted_minor  = $2,
       pending_minor = $3,
       version       = version + 1,
       updated_at    = now()
 WHERE account_id = $1
   AND version    = $4
`

type ApplyBalanceParams struct {
	AccountID    string
	PostedMinor  int64
	PendingMinor int64
	Version      int64
}

// ApplyBalance writes a new materialized balance.
//
// The version read under the lock goes into the WHERE clause. The row lock should
// already make a lost update impossible; this turns "should" into zero rows affected if
// it ever is not, which is far cheaper to diagnose than a reconciler alarm.
func (q *Queries) ApplyBalance(ctx context.Context, arg ApplyBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyBalance,
		arg.AccountID,
		arg.PostedMinor,
		arg.PendingMinor,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
    id, merchant_id, name, type, normal_balance, currency, allow_negative, metadata, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateAccountParams struct {
	ID            string
	MerchantID    string
	Name          string
	Type          AccountType
	NormalBalance BalanceSide
	Currency      string
	AllowNegative bool
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.Type,
		arg.NormalBalance,
		arg.Currency,
		arg.AllowNegative,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const derivedBalances = `-- name: DerivedBalances :many
SELECT a.id AS account_id,
       b.posted_minor AS materialized,
       COALESCE(SUM(
           CASE WHEN e.direction::text = a.normal_balance::text THEN e.amount_minor
                ELSE -e.amount_minor
           END
       ) FILTER (WHERE e.status = 'posted'), 0)::bigint AS derived
  FROM accounts a
  JOIN account_balances b ON b.account_id = a.id
  LEFT JOIN entries e ON e.account_id = a.id
 GROUP BY a.id, b.posted_minor
`

type DerivedBalancesRow struct {
	AccountID    string
	Materialized int64
	Derived      int64
}

func (q *Queries) DerivedBalances(ctx context.Context) ([]DerivedBalancesRow, error) {
	rows, err := q.db.Query(ctx, derivedBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DerivedBalancesRow{}
	for rows.Next() {
		var i DerivedBalancesRow
		if err := rows.Scan(&i.AccountID, &i.Materialized, &i.Derived); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const driftedAccounts = `-- name: DriftedAccounts :many
SELECT a.id AS account_id,
       b.posted_minor AS materialized,
       COALESCE(SUM(
           CASE WHEN e.direction::text = a.normal_balance::text THEN e.amount_minor
                ELSE -e.amount_minor
           END
       ) FILTER (WHERE e.status = 'posted'), 0)::bigint AS derived
  FROM accounts a
  JOIN account_balances b ON b.account_id = a.id
  LEFT JOIN entries e ON e.account_id = a.id
 GROUP BY a.id, b.posted_minor
HAVING b.posted_minor <> COALESCE(SUM(
           CASE WHEN e.direction::text = a.normal_balance::text THEN e.amount_minor
                ELSE -e.amount_minor
           END
       ) FILTER (WHERE e.status = 'posted'), 0)::bigint
`

type DriftedAccountsRow struct {
	AccountID    string
	Materialized int64
	Derived      int64
}

// DerivedBalances recomputes every account's posted balance from the entry log, which
// is the source of truth, and reports any account whose materialized balance disagrees
// (I7).
//
// DriftedAccounts returns only the accounts where the materialized balance and the
// balance derived from the entry log disagree. This is invariant I7, and a non-empty
// result is a P0 page: money has been created or destroyed somewhere.
func (q *Queries) DriftedAccounts(ctx context.Context) ([]DriftedAccountsRow, error) {
	rows, err := q.db.Query(ctx, driftedAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriftedAccountsRow{}
	for rows.Next() {
		var i DriftedAccountsRow
		if err := rows.Scan(&i.AccountID, &i.Materialized, &i.Derived); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, merchant_id, name, type, normal_balance, currency, allow_negative, metadata, created_at
  FROM accounts
 WHERE id = $1
`

type GetAccountRow struct {
	ID            string
	MerchantID    string
	Name          string
	Type          AccountType
	NormalBalance BalanceSide
	Currency      string
	AllowNegative bool
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetAccount(ctx context.Context, id string) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Type,
		&i.NormalBalance,
		&i.Currency,
		&i.AllowNegative,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT b.account_id, a.currency, b.posted_minor, b.pending_minor, b.version, b.updated_at
  FROM account_balances b
  JOIN accounts a ON a.id = b.account_id
 WHERE b.account_id = $1
`

type GetBalanceRow struct {
	AccountID    string
	Currency     string
	PostedMinor  int64
	PendingMinor int64
	Version      int64
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetBalance(ctx context.Context, accountID string) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var i GetBalanceRow
	err := row.Scan(
		&i.AccountID,
		&i.Currency,
		&i.PostedMinor,
		&i.PendingMinor,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, merchant_id, name, type, normal_balance, currency, allow_negative, metadata, created_at
  FROM accounts
 WHERE merchant_id = $1
 ORDER BY id
`

type ListAccountsRow struct {
	ID            string
	MerchantID    string
	Name          string
	Type          AccountType
	NormalBalance BalanceSide
	Currency      string
	AllowNegative bool
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListAccounts(ctx context.Context, merchantID string) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Type,
			&i.NormalBalance,
			&i.Currency,
			&i.AllowNegative,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT DISTINCT currency::text AS currency FROM accounts ORDER BY currency
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var currency string
		if err := rows.Scan(&currency); err != nil {
			return nil, err
		}
		items = append(items, currency)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccounts = `-- name: LockAccounts :many
SELECT a.id, a.merchant_id, a.name, a.type, a.normal_balance, a.currency,
       a.allow_negative, a.metadata, a.created_at,
       b.posted_minor, b.pending_minor, b.version, b.updated_at
  FROM account_balances b
  JOIN accounts a ON a.id = b.account_id
 WHERE b.account_id = ANY($1::text[])
 ORDER BY b.account_id
   FOR UPDATE OF b
`

type LockAccountsRow struct {
	ID            string
	MerchantID    string
	Name          string
	Type          AccountType
	NormalBalance BalanceSide
	Currency      string
	AllowNegative bool
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	PostedMinor   int64
	PendingMinor  int64
	Version       int64
	UpdatedAt     pgtype.Timestamptz
}

// LockAccounts is the first step of the critical section.
//
// ORDER BY before FOR UPDATE is the whole trick: it acquires the row locks in a total
// order, which makes deadlock structurally impossible rather than something to recover
// from by retrying. The caller sorts the ids it passes in as well, so the ordering is
// stated twice — once where a reader can see the intent, once where the database can
// act on it.
//
// FOR UPDATE OF b locks only the balance rows. Locking the account rows too would
// serialize unrelated writers against metadata that does not change during a movement.
func (q *Queries) LockAccounts(ctx context.Context, accountIds []string) ([]LockAccountsRow, error) {
	rows, err := q.db.Query(ctx, lockAccounts, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockAccountsRow{}
	for rows.Next() {
		var i LockAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Type,
			&i.NormalBalance,
			&i.Currency,
			&i.AllowNegative,
			&i.Metadata,
			&i.CreatedAt,
			&i.PostedMinor,
			&i.PendingMinor,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trialBalance = `-- name: TrialBalance :one
SELECT COALESCE(SUM(
           CASE WHEN a.type IN ('asset', 'expense') THEN b.posted_minor
                ELSE -b.posted_minor
           END
       ), 0)::bigint AS drift
  FROM account_balances b
  JOIN accounts a ON a.id = b.account_id
 WHERE a.currency = $1
`

// TrialBalance restates every posted balance in debit-positive terms and sums it. The
// reconciler asserts this is zero (I8); a non-zero result is a P0 page, not a metric to
// be smoothed over.
func (q *Queries) TrialBalance(ctx context.Context, currency string) (int64, error) {
	row := q.db.QueryRow(ctx, trialBalance, currency)
	var drift int64
	err := row.Scan(&drift)
	return drift, err
}
