// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, merchant_id, name, lookup, secret_hash, role, livemode, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
`

type CreateAPIKeyParams struct {
	ID         string
	MerchantID string
	Name       string
	Lookup     string
	SecretHash []byte
	Role       ApiKeyRole
	Livemode   bool
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.Lookup,
		arg.SecretHash,
		arg.Role,
		arg.Livemode,
	)
	return err
}

const findAPIKeyByLookup = `-- name: FindAPIKeyByLookup :one
SELECT id, merchant_id, name, lookup, secret_hash, role, livemode,
       last_used_at, revoked_at, created_at
  FROM api_keys
 WHERE lookup = $1
`

// FindAPIKeyByLookup resolves the non-secret lookup prefix to a stored key.
//
// The prefix exists so verification is one index seek plus one hash. Without it,
// argon2id — which is deliberately slow — would have to run once per stored key on every
// single request just to find which one matched.
func (q *Queries) FindAPIKeyByLookup(ctx context.Context, lookup string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByLookup, lookup)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Lookup,
		&i.SecretHash,
		&i.Role,
		&i.Livemode,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, merchant_id, name, lookup, secret_hash, role, livemode,
       last_used_at, revoked_at, created_at
  FROM api_keys
 WHERE merchant_id = $1
 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, merchantID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Lookup,
			&i.SecretHash,
			&i.Role,
			&i.Livemode,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
