// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const appendEntry = `-- name: AppendEntry :batchone
INSERT INTO entries (
    transaction_id, account_id, direction, amount_minor, currency, status, seq,
    balance_after, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, seq, created_at
`

type AppendEntryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AppendEntryParams struct {
	TransactionID string
	AccountID     string
	Direction     BalanceSide
	AmountMinor   int64
	Currency      string
	Status        EntryStatus
	Seq           int16
	BalanceAfter  int64
	CreatedAt     pgtype.Timestamptz
}

type AppendEntryRow struct {
	ID        int64
	Seq       int16
	CreatedAt pgtype.Timestamptz
}

// AppendEntry inserts one posting.
//
// Declared as a batch so that every entry of a transaction goes out in a single
// round trip via pgx.SendBatch, rather than one network hop per side of the double
// entry.
//
// The balance trigger is FOR EACH ROW and DEFERRABLE INITIALLY DEFERRED, so it queues a
// check per row and evaluates them all at COMMIT regardless of how the rows arrive. The
// batching is a latency decision, not a correctness one.
//
// seq comes back with the generated id because the caller has to match each id to the
// entry it belongs to.
//
// There is deliberately no UpdateEntry or DeleteEntry anywhere in this file. The
// database enforces that as well, with a rule, so the guarantee survives a manual psql
// session as readily as a future contributor.
func (q *Queries) AppendEntry(ctx context.Context, arg []AppendEntryParams) *AppendEntryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TransactionID,
			a.AccountID,
			a.Direction,
			a.AmountMinor,
			a.Currency,
			a.Status,
			a.Seq,
			a.BalanceAfter,
			a.CreatedAt,
		}
		batch.Queue(appendEntry, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AppendEntryBatchResults{br, len(arg), false}
}

func (b *AppendEntryBatchResults) QueryRow(f func(int, AppendEntryRow, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i AppendEntryRow
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&i.ID, &i.Seq, &i.CreatedAt)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *AppendEntryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
