// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package sqlc

import (
	"context"
)

const entriesByTransaction = `-- name: EntriesByTransaction :many
SELECT id, transaction_id, account_id, direction, amount_minor, currency, status, seq,
       balance_after, created_at
  FROM entries
 WHERE transaction_id = $1
 ORDER BY seq
`

func (q *Queries) EntriesByTransaction(ctx context.Context, transactionID string) ([]Entry, error) {
	rows, err := q.db.Query(ctx, entriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.Seq,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForAccountAsc = `-- name: EntriesForAccountAsc :many
SELECT id, transaction_id, account_id, direction, amount_minor, currency, status, seq,
       balance_after, created_at
  FROM entries
 WHERE account_id = $1
   AND id > $2
 ORDER BY id
 LIMIT $3
`

type EntriesForAccountAscParams struct {
	AccountID string
	ID        int64
	Limit     int32
}

// EntriesForAccountAsc replays an account's entries in write order. The reconciler uses
// it to bisect to the exact entry where the derived and materialized balances first
// disagreed, which is what balance_after is for.
func (q *Queries) EntriesForAccountAsc(ctx context.Context, arg EntriesForAccountAscParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, entriesForAccountAsc, arg.AccountID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.Seq,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, transaction_id, account_id, direction, amount_minor, currency, status, seq,
       balance_after, created_at
  FROM entries
 WHERE account_id = $1
   AND ($3::bigint IS NULL OR id < $3::bigint)
 ORDER BY id DESC
 LIMIT $2
`

type ListEntriesParams struct {
	AccountID string
	Limit     int32
	AfterID   *int64
}

// ListEntries pages an account's ledger view newest-first over the
// (account_id, id DESC) index.
//
// Entry ids are a BIGSERIAL, so descending id is descending time and the keyset is one
// comparison. OFFSET is never used: it degrades linearly with depth and, worse, silently
// skips or duplicates rows when concurrent inserts land between pages.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries, arg.AccountID, arg.Limit, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.Seq,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
