// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireIdempotencyKey = `-- name: AcquireIdempotencyKey :one
INSERT INTO idempotency_keys (
    id, merchant_id, idempotency_key, request_method, request_path, request_hash,
    state, recovery_point, lock_expires_at, request_id, created_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (merchant_id, idempotency_key) DO NOTHING
RETURNING id, merchant_id, idempotency_key, request_method, request_path, request_hash,
          state, recovery_point, lock_expires_at, response_status, response_body,
          resource_id, request_id, created_at, expires_at
`

type AcquireIdempotencyKeyParams struct {
	ID             string
	MerchantID     string
	IdempotencyKey string
	RequestMethod  string
	RequestPath    string
	RequestHash    []byte
	State          IdemState
	RecoveryPoint  string
	LockExpiresAt  pgtype.Timestamptz
	RequestID      *string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

// AcquireIdempotencyKey claims a key, or returns the row that already holds it.
//
// The insert-or-read has to be one statement. Checking and then inserting has a race in
// which two concurrent retries both believe they own the key, which is precisely the
// double-charge this table exists to prevent. ON CONFLICT DO NOTHING gives the loser an
// empty result, and the caller then reads the winner's row.
func (q *Queries) AcquireIdempotencyKey(ctx context.Context, arg AcquireIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, acquireIdempotencyKey,
		arg.ID,
		arg.MerchantID,
		arg.IdempotencyKey,
		arg.RequestMethod,
		arg.RequestPath,
		arg.RequestHash,
		arg.State,
		arg.RecoveryPoint,
		arg.LockExpiresAt,
		arg.RequestID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.State,
		&i.RecoveryPoint,
		&i.LockExpiresAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceID,
		&i.RequestID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const advanceIdempotencyKey = `-- name: AdvanceIdempotencyKey :execrows
UPDATE idempotency_keys
   SET recovery_point  = $2,
       lock_expires_at = $3
 WHERE id = $1
   AND state = 'in_progress'
`

type AdvanceIdempotencyKeyParams struct {
	ID            string
	RecoveryPoint string
	LockExpiresAt pgtype.Timestamptz
}

func (q *Queries) AdvanceIdempotencyKey(ctx context.Context, arg AdvanceIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceIdempotencyKey, arg.ID, arg.RecoveryPoint, arg.LockExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :execrows
UPDATE idempotency_keys
   SET state           = $2,
       recovery_point  = 'finished',
       response_status = $3,
       response_body   = $4,
       resource_id     = COALESCE($5, resource_id),
       lock_expires_at = NULL
 WHERE id = $1
`

type CompleteIdempotencyKeyParams struct {
	ID             string
	State          IdemState
	ResponseStatus *int32
	ResponseBody   []byte
	ResourceID     *string
}

// CompleteIdempotencyKey records the terminal outcome and the response to replay.
//
// Called inside the same transaction as the ledger write, so the entries and the
// response commit together. The lock is dropped in the same statement: a terminal record
// has no holder.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ID,
		arg.State,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys k
 WHERE k.id IN (
     SELECT doomed.id FROM idempotency_keys doomed
      WHERE doomed.expires_at < $1
      ORDER BY doomed.expires_at
      LIMIT $2
 )
`

type DeleteExpiredIdempotencyKeysParams struct {
	ExpiresAt pgtype.Timestamptz
	Limit     int32
}

// DeleteExpiredIdempotencyKeys is the reaper's batch. Bounded so a single sweep cannot
// lock the table for an unbounded time.
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, arg DeleteExpiredIdempotencyKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, merchant_id, idempotency_key, request_method, request_path, request_hash,
       state, recovery_point, lock_expires_at, response_status, response_body,
       resource_id, request_id, created_at, expires_at
  FROM idempotency_keys
 WHERE merchant_id = $1 AND idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	MerchantID     string
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.MerchantID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.State,
		&i.RecoveryPoint,
		&i.LockExpiresAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceID,
		&i.RequestID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :execrows
DELETE FROM idempotency_keys
 WHERE id = $1
   AND state = 'in_progress'
`

// ReleaseIdempotencyKey drops the lock without recording a response, so a retry after a
// server error genuinely re-executes rather than replaying a 500 forever.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIdempotencyKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeOverIdempotencyKey = `-- name: TakeOverIdempotencyKey :execrows
UPDATE idempotency_keys
   SET lock_expires_at = $2
 WHERE id = $1
   AND state = 'in_progress'
   AND (lock_expires_at IS NULL OR lock_expires_at <= now())
`

type TakeOverIdempotencyKeyParams struct {
	ID            string
	LockExpiresAt pgtype.Timestamptz
}

// TakeOverIdempotencyKey claims a record whose holder crashed.
//
// The lease comparison is in the WHERE clause, so this is a compare-and-set: of several
// retries arriving at once after a crash, exactly one wins and the rest are told to try
// again shortly.
func (q *Queries) TakeOverIdempotencyKey(ctx context.Context, arg TakeOverIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, takeOverIdempotencyKey, arg.ID, arg.LockExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
