// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeLiability AccountType = "liability"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeRevenue   AccountType = "revenue"
	AccountTypeExpense   AccountType = "expense"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type BalanceSide string

const (
	BalanceSideDebit  BalanceSide = "debit"
	BalanceSideCredit BalanceSide = "credit"
)

func (e *BalanceSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BalanceSide(s)
	case string:
		*e = BalanceSide(s)
	default:
		return fmt.Errorf("unsupported scan type for BalanceSide: %T", src)
	}
	return nil
}

type NullBalanceSide struct {
	BalanceSide BalanceSide
	Valid       bool // Valid is true if BalanceSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBalanceSide) Scan(value interface{}) error {
	if value == nil {
		ns.BalanceSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BalanceSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBalanceSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BalanceSide), nil
}

type EntryStatus string

const (
	EntryStatusPending EntryStatus = "pending"
	EntryStatusPosted  EntryStatus = "posted"
	EntryStatusVoided  EntryStatus = "voided"
)

func (e *EntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryStatus(s)
	case string:
		*e = EntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryStatus: %T", src)
	}
	return nil
}

type NullEntryStatus struct {
	EntryStatus EntryStatus
	Valid       bool // Valid is true if EntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryStatus), nil
}

type TxnStatus string

const (
	TxnStatusPending TxnStatus = "pending"
	TxnStatusPosted  TxnStatus = "posted"
	TxnStatusVoided  TxnStatus = "voided"
)

func (e *TxnStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxnStatus(s)
	case string:
		*e = TxnStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TxnStatus: %T", src)
	}
	return nil
}

type NullTxnStatus struct {
	TxnStatus TxnStatus
	Valid     bool // Valid is true if TxnStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxnStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TxnStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxnStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxnStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxnStatus), nil
}

type Account struct {
	ID            string
	MerchantID    string
	Name          string
	Type          AccountType
	NormalBalance BalanceSide
	Currency      string
	AllowNegative bool
	ShardOf       *string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
}

type AccountBalance struct {
	AccountID    string
	PostedMinor  int64
	PendingMinor int64
	Version      int64
	UpdatedAt    pgtype.Timestamptz
}

type Entry struct {
	ID            int64
	TransactionID string
	AccountID     string
	Direction     BalanceSide
	AmountMinor   int64
	Currency      string
	Status        EntryStatus
	Seq           int16
	BalanceAfter  int64
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID          string
	MerchantID  string
	Status      TxnStatus
	Currency    string
	Description string
	ReversesID  *string
	ExternalRef *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	PostedAt    pgtype.Timestamptz
}
