// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeLiability AccountType = "liability"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeRevenue   AccountType = "revenue"
	AccountTypeExpense   AccountType = "expense"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type ApiKeyRole string

const (
	ApiKeyRoleRead  ApiKeyRole = "read"
	ApiKeyRoleWrite ApiKeyRole = "write"
	ApiKeyRoleAdmin ApiKeyRole = "admin"
)

func (e *ApiKeyRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiKeyRole(s)
	case string:
		*e = ApiKeyRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiKeyRole: %T", src)
	}
	return nil
}

type NullApiKeyRole struct {
	ApiKeyRole ApiKeyRole
	Valid      bool // Valid is true if ApiKeyRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiKeyRole) Scan(value interface{}) error {
	if value == nil {
		ns.ApiKeyRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiKeyRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiKeyRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiKeyRole), nil
}

type BalanceSide string

const (
	BalanceSideDebit  BalanceSide = "debit"
	BalanceSideCredit BalanceSide = "credit"
)

func (e *BalanceSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BalanceSide(s)
	case string:
		*e = BalanceSide(s)
	default:
		return fmt.Errorf("unsupported scan type for BalanceSide: %T", src)
	}
	return nil
}

type NullBalanceSide struct {
	BalanceSide BalanceSide
	Valid       bool // Valid is true if BalanceSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBalanceSide) Scan(value interface{}) error {
	if value == nil {
		ns.BalanceSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BalanceSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBalanceSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BalanceSide), nil
}

type DeliveryState string

const (
	DeliveryStatePending    DeliveryState = "pending"
	DeliveryStateDelivering DeliveryState = "delivering"
	DeliveryStateSucceeded  DeliveryState = "succeeded"
	DeliveryStateExhausted  DeliveryState = "exhausted"
	DeliveryStateDisabled   DeliveryState = "disabled"
)

func (e *DeliveryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryState(s)
	case string:
		*e = DeliveryState(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryState: %T", src)
	}
	return nil
}

type NullDeliveryState struct {
	DeliveryState DeliveryState
	Valid         bool // Valid is true if DeliveryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryState) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryState), nil
}

type EndpointStatus string

const (
	EndpointStatusActive   EndpointStatus = "active"
	EndpointStatusDegraded EndpointStatus = "degraded"
	EndpointStatusDisabled EndpointStatus = "disabled"
)

func (e *EndpointStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndpointStatus(s)
	case string:
		*e = EndpointStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EndpointStatus: %T", src)
	}
	return nil
}

type NullEndpointStatus struct {
	EndpointStatus EndpointStatus
	Valid          bool // Valid is true if EndpointStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndpointStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EndpointStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndpointStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndpointStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndpointStatus), nil
}

type EntryStatus string

const (
	EntryStatusPending EntryStatus = "pending"
	EntryStatusPosted  EntryStatus = "posted"
	EntryStatusVoided  EntryStatus = "voided"
)

func (e *EntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryStatus(s)
	case string:
		*e = EntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryStatus: %T", src)
	}
	return nil
}

type NullEntryStatus struct {
	EntryStatus EntryStatus
	Valid       bool // Valid is true if EntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryStatus), nil
}

type IdemState string

const (
	IdemStateInProgress IdemState = "in_progress"
	IdemStateSucceeded  IdemState = "succeeded"
	IdemStateFailed     IdemState = "failed"
)

func (e *IdemState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdemState(s)
	case string:
		*e = IdemState(s)
	default:
		return fmt.Errorf("unsupported scan type for IdemState: %T", src)
	}
	return nil
}

type NullIdemState struct {
	IdemState IdemState
	Valid     bool // Valid is true if IdemState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdemState) Scan(value interface{}) error {
	if value == nil {
		ns.IdemState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdemState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdemState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdemState), nil
}

type TxnStatus string

const (
	TxnStatusPending TxnStatus = "pending"
	TxnStatusPosted  TxnStatus = "posted"
	TxnStatusVoided  TxnStatus = "voided"
)

func (e *TxnStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxnStatus(s)
	case string:
		*e = TxnStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TxnStatus: %T", src)
	}
	return nil
}

type NullTxnStatus struct {
	TxnStatus TxnStatus
	Valid     bool // Valid is true if TxnStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxnStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TxnStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxnStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxnStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxnStatus), nil
}

type Account struct {
	ID            string
	MerchantID    string
	Name          string
	Type          AccountType
	NormalBalance BalanceSide
	Currency      string
	AllowNegative bool
	ShardOf       *string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
}

type AccountBalance struct {
	AccountID    string
	PostedMinor  int64
	PendingMinor int64
	Version      int64
	UpdatedAt    pgtype.Timestamptz
}

type ApiKey struct {
	ID         string
	MerchantID string
	Name       string
	Lookup     string
	SecretHash []byte
	Role       ApiKeyRole
	Livemode   bool
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Entry struct {
	ID            int64
	TransactionID string
	AccountID     string
	Direction     BalanceSide
	AmountMinor   int64
	Currency      string
	Status        EntryStatus
	Seq           int16
	BalanceAfter  int64
	CreatedAt     pgtype.Timestamptz
}

type Event struct {
	ID           string
	MerchantID   string
	Type         string
	ResourceID   string
	Payload      []byte
	DispatchedAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type IdempotencyKey struct {
	ID             string
	MerchantID     string
	IdempotencyKey string
	RequestMethod  string
	RequestPath    string
	RequestHash    []byte
	State          IdemState
	RecoveryPoint  string
	LockExpiresAt  pgtype.Timestamptz
	ResponseStatus *int32
	ResponseBody   []byte
	ResourceID     *string
	RequestID      *string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type Transaction struct {
	ID          string
	MerchantID  string
	Status      TxnStatus
	Currency    string
	Description string
	ReversesID  *string
	ExternalRef *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	PostedAt    pgtype.Timestamptz
}

type WebhookAttempt struct {
	ID          int64
	DeliveryID  string
	Attempt     int32
	StatusCode  *int32
	Error       *string
	DurationMs  *int32
	AttemptedAt pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID             string
	EventID        string
	EndpointID     string
	MerchantID     string
	State          DeliveryState
	Attempt        int32
	NextAttemptAt  pgtype.Timestamptz
	LeasedUntil    pgtype.Timestamptz
	LastStatus     *int32
	LastError      *string
	LastDurationMs *int32
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type WebhookEndpoint struct {
	ID                  string
	MerchantID          string
	Url                 string
	EnabledEvents       []string
	Status              EndpointStatus
	ConsecutiveFailures int32
	Description         string
	CreatedAt           pgtype.Timestamptz
	DisabledAt          pgtype.Timestamptz
}

type WebhookSecret struct {
	ID         string
	EndpointID string
	SecretHash []byte
	SecretEnc  []byte
	Active     bool
	CreatedAt  pgtype.Timestamptz
	RetiredAt  pgtype.Timestamptz
}
