// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expirePendingTransactions = `-- name: ExpirePendingTransactions :many
SELECT id, merchant_id, status, currency, description, reverses_id, external_ref,
       metadata, created_at, posted_at
  FROM transactions
 WHERE status = 'pending'
   AND created_at < $1
 ORDER BY created_at
 LIMIT $2
`

type ExpirePendingTransactionsParams struct {
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

// ExpirePendingTransactions finds authorizations older than the TTL that were never
// captured or voided, so the sweep can release their holds.
func (q *Queries) ExpirePendingTransactions(ctx context.Context, arg ExpirePendingTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, expirePendingTransactions, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Status,
			&i.Currency,
			&i.Description,
			&i.ReversesID,
			&i.ExternalRef,
			&i.Metadata,
			&i.CreatedAt,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReversal = `-- name: FindReversal :one
SELECT id, merchant_id, status, currency, description, reverses_id, external_ref,
       metadata, created_at, posted_at
  FROM transactions
 WHERE reverses_id = $1
`

// FindReversal returns the mirror of a transaction, if one has been posted. The unique
// partial index on reverses_id is what actually prevents a double refund; this lookup
// turns the common case into a precise error rather than a constraint violation.
func (q *Queries) FindReversal(ctx context.Context, reversesID *string) (Transaction, error) {
	row := q.db.QueryRow(ctx, findReversal, reversesID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.Currency,
		&i.Description,
		&i.ReversesID,
		&i.ExternalRef,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, merchant_id, status, currency, description, reverses_id, external_ref,
       metadata, created_at, posted_at
  FROM transactions
 WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.Currency,
		&i.Description,
		&i.ReversesID,
		&i.ExternalRef,
		&i.Metadata,
		&i.CreatedAt,
		&i.PostedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (
    id, merchant_id, status, currency, description, reverses_id, external_ref,
    metadata, created_at, posted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type InsertTransactionParams struct {
	ID          string
	MerchantID  string
	Status      TxnStatus
	Currency    string
	Description string
	ReversesID  *string
	ExternalRef *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	PostedAt    pgtype.Timestamptz
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.MerchantID,
		arg.Status,
		arg.Currency,
		arg.Description,
		arg.ReversesID,
		arg.ExternalRef,
		arg.Metadata,
		arg.CreatedAt,
		arg.PostedAt,
	)
	return err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, merchant_id, status, currency, description, reverses_id, external_ref,
       metadata, created_at, posted_at
  FROM transactions
 WHERE merchant_id = $1
   AND ($3::text IS NULL OR external_ref = $3::text)
   AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
 ORDER BY created_at DESC, id DESC
 LIMIT $2
`

type ListTransactionsParams struct {
	MerchantID    string
	Limit         int32
	ExternalRef   *string
	CreatedBefore pgtype.Timestamptz
}

// ListTransactions pages a merchant's transactions newest-first over the
// (merchant_id, created_at DESC, id DESC) index.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.MerchantID,
		arg.Limit,
		arg.ExternalRef,
		arg.CreatedBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Status,
			&i.Currency,
			&i.Description,
			&i.ReversesID,
			&i.ExternalRef,
			&i.Metadata,
			&i.CreatedAt,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionStatus = `-- name: SetTransactionStatus :execrows
UPDATE transactions
   SET status    = $2,
       posted_at = COALESCE($3, posted_at)
 WHERE id = $1
`

type SetTransactionStatusParams struct {
	ID       string
	Status   TxnStatus
	PostedAt pgtype.Timestamptz
}

func (q *Queries) SetTransactionStatus(ctx context.Context, arg SetTransactionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTransactionStatus, arg.ID, arg.Status, arg.PostedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
