// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeWebhookEndpoints = `-- name: ActiveWebhookEndpoints :many
SELECT id, merchant_id, url, enabled_events, status, consecutive_failures,
       description, created_at, disabled_at
  FROM webhook_endpoints
 WHERE merchant_id = $1 AND status <> 'disabled'
 ORDER BY id
`

// ActiveWebhookEndpoints returns the endpoints an event may fan out to. A disabled
// endpoint is excluded here rather than filtered later, so a disabled endpoint never
// gets a delivery row created for it at all.
func (q *Queries) ActiveWebhookEndpoints(ctx context.Context, merchantID string) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, activeWebhookEndpoints, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Url,
			&i.EnabledEvents,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.Description,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeWebhookSecrets = `-- name: ActiveWebhookSecrets :many
SELECT id, endpoint_id, secret_hash, secret_enc, active, created_at, retired_at
  FROM webhook_secrets
 WHERE endpoint_id = $1 AND active
 ORDER BY created_at DESC
`

func (q *Queries) ActiveWebhookSecrets(ctx context.Context, endpointID string) ([]WebhookSecret, error) {
	rows, err := q.db.Query(ctx, activeWebhookSecrets, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSecret{}
	for rows.Next() {
		var i WebhookSecret
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.SecretHash,
			&i.SecretEnc,
			&i.Active,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appendEvent = `-- name: AppendEvent :exec

INSERT INTO events (id, merchant_id, type, resource_id, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendEventParams struct {
	ID         string
	MerchantID string
	Type       string
	ResourceID string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

// ── the outbox ───────────────────────────────────────────────────────────────
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.Exec(ctx, appendEvent,
		arg.ID,
		arg.MerchantID,
		arg.Type,
		arg.ResourceID,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
UPDATE webhook_deliveries
   SET state = 'delivering',
       leased_until = $2
 WHERE id IN (
     SELECT id FROM webhook_deliveries
      WHERE state = 'pending'
        AND next_attempt_at <= now()
      ORDER BY next_attempt_at
      LIMIT $1
        FOR UPDATE SKIP LOCKED
 )
RETURNING id, event_id, endpoint_id, merchant_id, state, attempt, next_attempt_at,
          leased_until, last_status, last_error, last_duration_ms, created_at, completed_at
`

type ClaimDueDeliveriesParams struct {
	Limit       int32
	LeasedUntil pgtype.Timestamptz
}

// ClaimDueDeliveries is the canonical Postgres work queue.
//
// FOR UPDATE SKIP LOCKED makes competing consumers correct without any coordination:
// each worker takes rows the others are not holding. Adding workers adds throughput
// rather than contention, which is the entire reason Postgres is the queue here and no
// broker is involved.
//
// The lease is set in the same statement as the claim, so a worker that dies immediately
// after claiming still leaves a row that the sweeper can reclaim.
func (q *Queries) ClaimDueDeliveries(ctx context.Context, arg ClaimDueDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveries, arg.Limit, arg.LeasedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.MerchantID,
			&i.State,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LeasedUntil,
			&i.LastStatus,
			&i.LastError,
			&i.LastDurationMs,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimUndispatchedEvents = `-- name: ClaimUndispatchedEvents :many
SELECT id, merchant_id, type, resource_id, payload, dispatched_at, created_at
  FROM events
 WHERE dispatched_at IS NULL
 ORDER BY id
 LIMIT $1
   FOR UPDATE SKIP LOCKED
`

// ClaimUndispatched takes a batch of events that have not been fanned out.
//
// SKIP LOCKED is what lets several dispatchers run at once with no coordination: each
// takes rows the others are not holding, so an event is never expanded twice
// concurrently. The unique constraint on (event_id, endpoint_id) covers the case where
// one of them crashed after inserting some deliveries.
func (q *Queries) ClaimUndispatchedEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, claimUndispatchedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Type,
			&i.ResourceID,
			&i.Payload,
			&i.DispatchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDelivery = `-- name: CompleteDelivery :execrows
UPDATE webhook_deliveries
   SET state = $1,
       attempt = attempt + 1,
       leased_until = NULL,
       last_status = $2,
       last_error = $3,
       last_duration_ms = $4,
       completed_at = now()
 WHERE id = $5
`

type CompleteDeliveryParams struct {
	State          DeliveryState
	LastStatus     *int32
	LastError      *string
	LastDurationMs *int32
	ID             string
}

func (q *Queries) CompleteDelivery(ctx context.Context, arg CompleteDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeDelivery,
		arg.State,
		arg.LastStatus,
		arg.LastError,
		arg.LastDurationMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDeliveriesByState = `-- name: CountDeliveriesByState :many
SELECT state, count(*)::bigint AS total
  FROM webhook_deliveries
 GROUP BY state
`

type CountDeliveriesByStateRow struct {
	State DeliveryState
	Total int64
}

func (q *Queries) CountDeliveriesByState(ctx context.Context) ([]CountDeliveriesByStateRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDeliveriesByStateRow{}
	for rows.Next() {
		var i CountDeliveriesByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :exec

INSERT INTO webhook_endpoints (id, merchant_id, url, enabled_events, description, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebhookEndpointParams struct {
	ID            string
	MerchantID    string
	Url           string
	EnabledEvents []string
	Description   string
	CreatedAt     pgtype.Timestamptz
}

// ── endpoints ────────────────────────────────────────────────────────────────
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, createWebhookEndpoint,
		arg.ID,
		arg.MerchantID,
		arg.Url,
		arg.EnabledEvents,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const createWebhookSecret = `-- name: CreateWebhookSecret :exec

INSERT INTO webhook_secrets (id, endpoint_id, secret_hash, secret_enc, active, created_at)
VALUES ($1, $2, $3, $4, TRUE, $5)
`

type CreateWebhookSecretParams struct {
	ID         string
	EndpointID string
	SecretHash []byte
	SecretEnc  []byte
	CreatedAt  pgtype.Timestamptz
}

// ── secrets ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateWebhookSecret(ctx context.Context, arg CreateWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, createWebhookSecret,
		arg.ID,
		arg.EndpointID,
		arg.SecretHash,
		arg.SecretEnc,
		arg.CreatedAt,
	)
	return err
}

const enqueueDelivery = `-- name: EnqueueDelivery :exec

INSERT INTO webhook_deliveries (id, event_id, endpoint_id, merchant_id, state, next_attempt_at, created_at)
VALUES ($1, $2, $3, $4, 'pending', now(), now())
ON CONFLICT (event_id, endpoint_id) DO NOTHING
`

type EnqueueDeliveryParams struct {
	ID         string
	EventID    string
	EndpointID string
	MerchantID string
}

// ── the delivery queue ───────────────────────────────────────────────────────
// EnqueueDelivery is idempotent on (event_id, endpoint_id), so re-running a dispatch
// that crashed part way through cannot produce a second delivery to the same endpoint.
//
// The due time comes from now() rather than a parameter, because it is compared against
// now() when the row is claimed. Passing the application's clock instead couples the two:
// a deployment whose app clock runs ahead of the database's would delay every first
// attempt by the skew, and the queue would look mysteriously slow.
func (q *Queries) EnqueueDelivery(ctx context.Context, arg EnqueueDeliveryParams) error {
	_, err := q.db.Exec(ctx, enqueueDelivery,
		arg.ID,
		arg.EventID,
		arg.EndpointID,
		arg.MerchantID,
	)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, merchant_id, type, resource_id, payload, dispatched_at, created_at
  FROM events
 WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.ResourceID,
		&i.Payload,
		&i.DispatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEventForMerchant = `-- name: GetEventForMerchant :one
SELECT id, merchant_id, type, resource_id, payload, dispatched_at, created_at
  FROM events
 WHERE merchant_id = $1 AND id = $2
`

type GetEventForMerchantParams struct {
	MerchantID string
	ID         string
}

func (q *Queries) GetEventForMerchant(ctx context.Context, arg GetEventForMerchantParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForMerchant, arg.MerchantID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.ResourceID,
		&i.Payload,
		&i.DispatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, merchant_id, url, enabled_events, status, consecutive_failures,
       description, created_at, disabled_at
  FROM webhook_endpoints
 WHERE merchant_id = $1 AND id = $2
`

type GetWebhookEndpointParams struct {
	MerchantID string
	ID         string
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, arg.MerchantID, arg.ID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Url,
		&i.EnabledEvents,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.Description,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, merchant_id, url, enabled_events, status, consecutive_failures,
       description, created_at, disabled_at
  FROM webhook_endpoints
 WHERE id = $1
`

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Url,
		&i.EnabledEvents,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.Description,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const incrementEndpointFailures = `-- name: IncrementEndpointFailures :one
UPDATE webhook_endpoints
   SET consecutive_failures = consecutive_failures + 1
 WHERE id = $1
RETURNING consecutive_failures
`

func (q *Queries) IncrementEndpointFailures(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementEndpointFailures, id)
	var consecutive_failures int32
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, event_id, endpoint_id, merchant_id, state, attempt, next_attempt_at,
       leased_until, last_status, last_error, last_duration_ms, created_at, completed_at
  FROM webhook_deliveries
 WHERE endpoint_id = $1
   AND ($3::delivery_state IS NULL OR state = $3::delivery_state)
 ORDER BY created_at DESC
 LIMIT $2
`

type ListDeliveriesParams struct {
	EndpointID string
	Limit      int32
	State      *DeliveryState
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, arg.EndpointID, arg.Limit, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.MerchantID,
			&i.State,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LeasedUntil,
			&i.LastStatus,
			&i.LastError,
			&i.LastDurationMs,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, merchant_id, type, resource_id, payload, dispatched_at, created_at
  FROM events
 WHERE merchant_id = $1
   AND ($3::text IS NULL OR id < $3::text)
 ORDER BY id DESC
 LIMIT $2
`

type ListEventsParams struct {
	MerchantID string
	Limit      int32
	BeforeID   *string
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.MerchantID, arg.Limit, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Type,
			&i.ResourceID,
			&i.Payload,
			&i.DispatchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, merchant_id, url, enabled_events, status, consecutive_failures,
       description, created_at, disabled_at
  FROM webhook_endpoints
 WHERE merchant_id = $1
 ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, merchantID string) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Url,
			&i.EnabledEvents,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.Description,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventsDispatched = `-- name: MarkEventsDispatched :execrows
UPDATE events SET dispatched_at = now() WHERE id = ANY($1::text[])
`

func (q *Queries) MarkEventsDispatched(ctx context.Context, dollar_1 []string) (int64, error) {
	result, err := q.db.Exec(ctx, markEventsDispatched, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const oldestPendingDelivery = `-- name: OldestPendingDelivery :one
SELECT COALESCE(EXTRACT(EPOCH FROM (now() - MIN(next_attempt_at))), 0)::bigint AS oldest_seconds
  FROM webhook_deliveries
 WHERE state IN ('pending', 'delivering')
`

// OldestPendingDelivery backs the real service-level indicator: not how many deliveries
// are queued, but how long the oldest one has been waiting.
func (q *Queries) OldestPendingDelivery(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, oldestPendingDelivery)
	var oldest_seconds int64
	err := row.Scan(&oldest_seconds)
	return oldest_seconds, err
}

const reclaimExpiredLeases = `-- name: ReclaimExpiredLeases :execrows
UPDATE webhook_deliveries
   SET state = 'pending',
       leased_until = NULL
 WHERE state = 'delivering'
   AND leased_until IS NOT NULL
   AND leased_until < $1
`

// ReclaimExpiredLeases is the crash-recovery path: a worker that died mid-POST left a
// row marked delivering with a lease that has now passed.
//
// This is precisely why delivery is at-least-once. The worker may have died after the
// endpoint accepted the request but before recording it, so the event will be sent
// again — which is why consumers are told to dedupe on the event id.
func (q *Queries) ReclaimExpiredLeases(ctx context.Context, leasedUntil pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimExpiredLeases, leasedUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDeliveryAttempt = `-- name: RecordDeliveryAttempt :exec
INSERT INTO webhook_attempts (delivery_id, attempt, status_code, error, duration_ms, attempted_at)
VALUES ($1, $2, $3,
        $4, $5, $6)
`

type RecordDeliveryAttemptParams struct {
	DeliveryID  string
	Attempt     int32
	StatusCode  *int32
	Error       *string
	DurationMs  *int32
	AttemptedAt pgtype.Timestamptz
}

func (q *Queries) RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, recordDeliveryAttempt,
		arg.DeliveryID,
		arg.Attempt,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
		arg.AttemptedAt,
	)
	return err
}

const replayDelivery = `-- name: ReplayDelivery :execrows
UPDATE webhook_deliveries
   SET state = 'pending',
       attempt = 0,
       next_attempt_at = now(),
       leased_until = NULL,
       completed_at = NULL
 WHERE id = $1
   AND merchant_id = $2
   AND state = 'exhausted'
`

type ReplayDeliveryParams struct {
	ID         string
	MerchantID string
}

// ReplayDelivery moves an exhausted delivery back into the queue.
//
// The state check is in the WHERE clause rather than in the caller, so replaying a
// delivery that is already pending cannot reset its attempt counter and hand it a fresh
// retry budget it has not earned.
func (q *Queries) ReplayDelivery(ctx context.Context, arg ReplayDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, replayDelivery, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleDelivery = `-- name: RescheduleDelivery :execrows
UPDATE webhook_deliveries
   SET state = 'pending',
       attempt = attempt + 1,
       next_attempt_at = now() + make_interval(secs => $1::float8),
       leased_until = NULL,
       last_status = $2,
       last_error = $3,
       last_duration_ms = $4
 WHERE id = $5
`

type RescheduleDeliveryParams struct {
	DelaySeconds   float64
	LastStatus     *int32
	LastError      *string
	LastDurationMs *int32
	ID             string
}

// The backoff arrives as a delay rather than an absolute instant, for the same reason:
// the schedule is relative to the database's clock, which is the one the claim reads.
func (q *Queries) RescheduleDelivery(ctx context.Context, arg RescheduleDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleDelivery,
		arg.DelaySeconds,
		arg.LastStatus,
		arg.LastError,
		arg.LastDurationMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetEndpointFailures = `-- name: ResetEndpointFailures :execrows
UPDATE webhook_endpoints SET consecutive_failures = 0 WHERE id = $1
`

func (q *Queries) ResetEndpointFailures(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, resetEndpointFailures, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireWebhookSecret = `-- name: RetireWebhookSecret :execrows
UPDATE webhook_secrets SET active = FALSE, retired_at = now() WHERE id = $1
`

func (q *Queries) RetireWebhookSecret(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, retireWebhookSecret, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWebhookEndpointStatus = `-- name: SetWebhookEndpointStatus :execrows
UPDATE webhook_endpoints
   SET status = $1::endpoint_status,
       disabled_at = CASE
           WHEN $1::endpoint_status = 'disabled'::endpoint_status THEN now()
           ELSE disabled_at
       END
 WHERE id = $2
`

type SetWebhookEndpointStatusParams struct {
	Status EndpointStatus
	ID     string
}

// Both uses of the status parameter are cast to endpoint_status explicitly. Without the
// casts Postgres deduces text in the CASE and the enum in the assignment, decides the
// two are inconsistent, and refuses the whole statement — which showed up as an endpoint
// that answered 410 and was never actually disabled.
func (q *Queries) SetWebhookEndpointStatus(ctx context.Context, arg SetWebhookEndpointStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWebhookEndpointStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
